using System.Collections.Generic;

namespace DogMatch.Shared.References
{
    public class ColorsMasterList
    {
        public IEnumerable<string> ColorMasterList = new string[]
        {
            "Albino",
            "Apricot",
            "ASCOB",
            "Ash",
            "Badger",
            "Banding",
            "Beauty spot",
            "Belge",
            "Belton",
            "Bi-black",
            "Bi-blue",
            "Biscuit",
            "Black",
            "Black and silver",
            "Black brindle",
            "Blenheim",
            "Blue",
            "Blue fawn",
            "Blue roan",
            "Boston",
            "Brindlequin",
            "Bronzing",
            "Brown",
            "Buff",
            "Butterfly nose",
            "Charcoal",
            "Check",
            "Chestnut",
            "Chocolate",
            "Cinnamon",
            "Clear-colored",
            "Copper",
            "Cream",
            "Creeping tan",
            "Cryptic merle",
            "Dapple",
            "Dark merle",
            "Deadgrass",
            "Deer",
            "Dilute spot",
            "Domino",
            "Dorsal stripe",
            "Dudley nose",
            "Fallow",
            "Fawn",
            "Fawnequin",
            "Fawn merle",
            "Flashy",
            "Flecking",
            "Flowered",
            "Formentino",
            "Ginger merle",
            "Gold",
            "Green",
            "Grey",
            "Grizzle",
            "Harlequin",
            "Havana Brown",
            "Isabella",
            "Ivory",
            "King Charles",
            "Lavender",
            "Lemon",
            "Light red (and red)",
            "Lilac",
            "Lion",
            "Mahogany",
            "Maltese blue",
            "Mantle",
            "Mask",
            "Merlequin (aka merlekin, merlikin)",
            "Minimal merle",
            "Mosaic",
            "Mosaic spot",
            "Muddy merle",
            "Mustard",
            "Onyx brindle",
            "Orange",
            "Particolor",
            "Pearl",
            "Pencilling",
            "Pepper",
            "Phantom merle",
            "Pinto",
            "Pips",
            "Platinum",
            "Plattenhunde",
            "Points",
            "Porcelaine",
            "Powder merle",
            "Prince Charles",
            "Red",
            "Red speckle",
            "Reverse brindle",
            "Ruby",
            "Russet",
            "Rust",
            "Sable",
            "Salt and pepper",
            "Sandy",
            "Seal",
            "Sedge",
            "Sesame",
            "Silver brindle",
            "Slate",
            "Slate merle",
            "Sooty",
            "Spectacles",
            "Splash coat",
            "Stag",
            "Tan",
            "Tawny",
            "Tiger brindle",
            "Tricolor",
            "Trim",
            "Trindle",
            "Tweed (tweed merle)",
            "Urajiro",
            "Vent marking",
            "Wheaten",
            "White",
            "White collar",
            "Widow's peak",
            "Wolf grey",
            "Yellow",
        };
    }
}
